version: '3'

volumes:
  mariadb-volume:
    name: mariadb-volume
    driver: local
    driver_opts:
      type: none
      device: ./ychun/data/mariadb
      o: bind
  wordpress-volume:
    name: wordpress-volume
    driver: local
    driver_opts:
      type: none
      device: ./ychun/data/wordpress
      o: bind
services:
  mariadb:
    image: mariadb
    restart: always
    build:
      context: ./requirements/mariadb
      args:
        - WP_USER
        - WP_PASSWORD
        - WP_DATABASE
    expose:
      - "3306"
    volumes:
      - mariadb-volume:/var/database
    networks:
      intra:
        ipv4_address: 172.31.0.11
    tty: true
  wordpress:
    image: wordpress
    restart: always
    build:
      context: ./requirements/wordpress
      args:
        - WP_USER
        - WP_PASSWORD
        - WP_DATABASE
    volumes:
      - wordpress-volume:/var/www/html
    expose:
      - "9000"
    networks:
      intra:
        ipv4_address: 172.31.0.12
    tty: true
  nginx:
    image: nginx
    restart: always
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress-volume:/var/www/html
    networks:
      intra:
        ipv4_address: 172.31.0.13
    tty: true

networks:
  intra:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/16
